import {createEvidenceModel} from '../data/evidence-model.js';
import {buildEvidenceNavigation} from './evidence-navigation.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))&&v!==''&&v!==null&&v!==undefined?Number(v).toLocaleString(undefined,{maximumFractionDigits:3}):'Not supplied';
const kv=rows=>'<dl class="evidence-kv">'+rows.filter(([,v])=>v!==null&&v!==undefined&&v!=='').map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')+'</dl>';
const title=v=>v.replaceAll('_',' ');
export async function createEvidenceView({data,temporal,city,fabric,groups,interaction,invalidate,host,renderer:providedRenderer=null,flatMode=false}){
 const [derived,routes]=await Promise.all(['./data/evidence-map.json','./data/dashboard-routes.json'].map(async path=>{const r=await fetch(path);if(!r.ok)throw new Error('Evidence metadata HTTP '+r.status);return r.json();}));
 if(!providedRenderer)throw new Error('Evidence renderer is required');
 const model=createEvidenceModel(data,derived,temporal.model),renderer=providedRenderer;let selected=null,selectedConflict=null,selectedEdge=null,chosen=new Set(),type='',status='',cell='',issuesOnly=false,showConflicts=false,showEdges=false,scope=flatMode?'cells':'selected',layers=[],lastAllowed=true,lastCellSignature='',disposed=false,lastDrawKey='',lastIssueKey='';
 const toolbar=document.createElement('div');toolbar.className='evidence-toolbar';toolbar.innerHTML='<label><input type="checkbox" id="issuesOnly"> Issues only</label><label><input type="checkbox" id="showConflictMarkers"> Conflict markers</label><label>Type <select id="issueType"><option value="">All recorded types</option></select></label><label>Status <select id="issueStatus"><option value="">All statuses</option></select></label><label><input type="checkbox" id="sharedEdges"> Shared edges</label><label>Source scope <select id="sourceScope"><option value="selected">Selected parcel</option><option value="cells">Visible cells</option></select></label><span id="issueSummary" role="status"></span>';
 document.querySelector('.temporal-bar').after(toolbar);document.querySelector('#sourceScope').value=scope;city.setSourceScope?.(scope);for(const [id,values] of [['issueType',model.types],['issueStatus',model.statuses]])for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=title(value);document.querySelector('#'+id).append(o);}
 const legend=document.createElement('div');legend.className='evidence-legend';legend.hidden=true;host.append(legend);
 const api=()=>window.PRAMAN_SPATIAL_VIEW;
 function allowed(){const t=temporal.getState();return t.point==='current'&&!t.playback&&t.mode!=='historical';}
 function context(){const c=model.conflicts.get(selectedConflict),observationIds=[...chosen];if(c)observationIds.push(...c.observationIds);const types=[...new Set(observationIds.map(id=>model.observations.get(id)?.sourceType).filter(Boolean))];return {openConflictIds:model.conflictsFor(selected).filter(c=>c.review_status==='OPEN').map(c=>c.id),parcelId:selected,conflictId:c?.parcel_id===selected?c.id:null,sourceIds:types.map(t=>data.sourceMetadata.find(s=>s.type===t)?.id||t),observationIds:[...new Set(observationIds)],sourceType:types[0]||'',type,status,cell,issues:issuesOnly};}
 function href(target){return buildEvidenceNavigation(target,context(),{...routes,...window.PRAMAN_DASHBOARD_PATHS},location.href);}
 function link(target,label){if(!selected||target==='reconciliation'&&!selectedConflict)return '';return `<a data-evidence-nav="${target}" href="${esc(href(target))}" class="evidence-link">${esc(label)}</a>`;}
 function renderDecisionSupport(pid){const s=model.selected(pid);if(!s.parcel)return '';const explain=model.why(pid),fields=s.scores?.confidence||{};const labels={overall_match_confidence:'Match confidence',geometry_confidence:'Geometry confidence',ownership_confidence:'Ownership confidence',land_use_confidence:'Land-use confidence',lineage_confidence:'Lineage confidence',reconciliation_confidence:'Reconciliation confidence'};
  return `<section class="panel-section"><h3>System decision support</h3><span class="evidence-badge">${esc(s.authority)}</span>${kv([['Review / matching status',s.reconciliation?.matchStatus],['Human review required',s.reconciliation?.requiresHumanReview],['Recorded reconciliation note',s.scores?.reason],...Object.entries(fields).map(([k,v])=>[labels[k]||title(k),num(v)])])}${s.reconciliation?`<details><summary>System proposal · separate from authority</summary><p>Reconciliation output is not an approval. Geometry acceptance remains governed by the authoritative registry.</p><pre>${esc(JSON.stringify(s.reconciliation.proposedState,null,2))}</pre><strong>Stored authoritative-state reference</strong><pre>${esc(JSON.stringify(s.reconciliation.authoritativeState,null,2))}</pre></details>`:''}<details class="why-match"><summary>Why this match?</summary><p>${esc(explain.limitation)}</p><p>Recorded membership: ${esc(explain.association)}. These are the supplied dimensions, not a reconstructed scoring formula.</p>${explain.observations.map(o=>`<details><summary>${esc(o.id)} · ${esc(o.source)}</summary>${kv([['Source record',o.sourceRecordId],['Source parcel identifier',o.sourceParcelId],['Geometry confidence',o.geometryConfidence],['Identifier confidence',o.identifierConfidence],['Attribute confidence',o.attributeConfidence],['Temporal freshness',o.temporalFreshness],['Source reliability',o.sourceReliability],['Positional accuracy (m)',o.positionalAccuracyMetres],['Observed area (m²)',o.observedArea],['Observation date',o.date],['Recorded holder',o.holder],['Land use',o.landUse]])}<pre>${esc(o.sourceDetails)}</pre></details>`).join('')}</details>${link('evidenceGraph','View Evidence')}</section>`;
 }
 function comparisonHTML(pid,oid){const c=model.comparison(pid,oid);if(!c)return '<p>No supplied geometry pair available. No shape is substituted.</p>';const m=c.metrics;return `<details class="geometry-measurements" ${chosen.has(oid)?'open':''}><summary>Measured geometry comparison</summary><p>Display diagnostics against the stored ${esc(temporal.model.selected(pid)?.category)} reference. These measurements do not create a conflict classification or prove matcher reasoning.</p>${kv([['Reference geometry',c.canonicalGeometryId],['Observation geometry',c.sourceGeometryId],['Centroid offset (m)',num(m.centroidOffsetMetres)],['Discrete boundary Hausdorff (m)',num(m.discreteBoundaryHausdorffMetres)],['Signed observation − reference area (m²)',num(m.signedAreaDifferenceSqm)],['Overlap (m²)',num(m.overlapSqm)],['Reference-only area (m²)',num(m.canonicalOnlySqm)],['Observation-only area (m²)',num(m.sourceOnlySqm)],['Intersection / union',num(m.intersectionOverUnion)],['Components: reference / observation',m.canonicalComponents+' / '+m.sourceComponents],['Holes: reference / observation',m.canonicalHoles+' / '+m.sourceHoles]])}<p>Amber: reference-only; blue: observation-only; solid reference edges and dashed observation edges. The line between centroids is a measured offset, not a correction vector. Unmatched edges use exact geometric difference. No legal gap/sliver label is inferred.</p></details>`;}
 function topologyHTML(pid){const intersections=derived.canonicalOverlaps.filter(r=>r.parcelIds.includes(pid));return `<details><summary>Neighbour topology diagnostics (${intersections.length} canonical overlap pairs)</summary><p>Measured intersections of stored canonical polygons, not newly assigned conflict labels. No geometry was repaired.</p>${intersections.map(r=>`<p>${esc(r.parcelIds.find(id=>id!==pid))} · overlap ${num(r.overlapSqm)} m²</p>`).join('')||'<p>No positive-area canonical overlap derived for this parcel.</p>'}</details>`;}
 function edgeHTML(pid){const edges=model.selected(pid).edges;if(!edges.length)return '<p>No exact shared canonical boundary is derived for this parcel. Nearby or mismatched edges are not snapped into a shared edge.</p>';const edge=selectedEdge&&model.edges.get(selectedEdge);return `<details class="edge-inspection" ${edge?'open':''}><summary>Shared boundary inspection (${edges.length})</summary><label>Canonical shared edge <select data-edge-select><option value="">Choose one shared edge</option>${edges.map(e=>`<option value="${e.id}" ${e.id===selectedEdge?'selected':''}>${esc(e.parcelIds.find(id=>id!==pid))} · ${num(e.lengthMetres)} m</option>`).join('')}</select></label>${edge?`<p><strong>${esc(edge.id)}</strong> · one boundary record for both neighbours.</p>${edge.parcelIds.map((id,i)=>`<button type="button" data-edge-neighbour="${esc(id)}">Side ${i===0?'A':'B'} · ${esc(id)}</button>${kv([['Geometry',model.parcels.get(id)?.geometryId],['Stored authority',temporal.model.selected(id)?.category],['Reconciliation / review',model.reconciliation.get(id)?.matchStatus],['Geometry acceptance',temporal.model.geometries.get(model.parcels.get(id)?.geometryId)?.acceptedStatus]])}`).join('')}<p>No edge-level correction decision or source attribution table is supplied. The following observations belong to the neighbouring parcels; their measured offsets do not establish legal contribution.</p>${edge.observations.map(o=>`<details><summary>${esc(o.observationId)} · sampled max offset ${num(o.sampledMaxOffsetMetres)} m</summary><p>${esc(o.parcelId)} · ${esc(model.observations.get(o.observationId)?.sourceType)}. Three nearest-boundary samples per shared segment; not a maximum over the continuous boundary.</p><button type="button" data-edge-observation="${esc(o.observationId)}" data-owner-parcel="${esc(o.parcelId)}">Compare this observation</button></details>`).join('')}<h4>Related parcel conflicts — no edge-specific attribution supplied</h4>${edge.parcelIds.flatMap(id=>model.conflictsFor(id)).map(c=>`<button type="button" data-conflict="${esc(c.id)}">${esc(c.id)} · ${esc(c.type)} · ${esc(c.review_status)}</button>`).join('')||'<p>No related conflict records.</p>'}`:''}</details>`;}
 function renderSources(pid){const s=model.selected(pid);return `<section class="panel-section"><h3>Source comparison</h3><p>Solid canonical reference: ${esc(s.authority)}. Dashed outlines: SOURCE OBSERVATION, with mixed acquisition dates. A source record never replaces authority.</p>${s.sources.length?s.sources.map(o=>`<details class="source-observation" ${chosen.has(o.id)?'open':''}><summary>${esc(o.sourceType)} · ${esc(o.id)}</summary><label><input type="checkbox" data-observation="${esc(o.id)}" ${chosen.has(o.id)?'checked':''} ${o.geometry?'':'disabled'}> Compare supplied geometry</label>${kv([['Source record',o.sourceRecordId],['Date',o.date],['Geometry',o.geometry?o.geometryId:'Not supplied — no overlay'],['Holder',o.owner],['Observed area (m²)',num(o.observedArea)],['Source reliability',o.sourceReliability],['Positional accuracy (m)',o.positionalAccuracyMetres]])}${o.geometry?comparisonHTML(pid,o.id):''}</details>`).join(''):'<p>No source observations supplied.</p>'}${edgeHTML(pid)}${topologyHTML(pid)}${link('evidenceGraph','View Evidence')}</section>`;}
 function renderConflicts(pid){const rows=model.conflictsFor(pid);return `<section class="panel-section"><h3>Recorded conflicts (${rows.length})</h3><p>Markers locate parcel records. They are not conflict footprints. Only actual evidence geometry is compared.</p>${rows.map(c=>`<details class="conflict-record" ${c.id===selectedConflict?'open':''}><summary>${esc(c.id)} · ${esc(c.type)} · ${esc(c.review_status)}</summary><button type="button" data-conflict="${esc(c.id)}">Locate / inspect conflict</button>${kv([['Type',c.type],['Attribute / geometry',c.attributeOrGeometry],['Source A',c.source_a],['Value A',c.observed_a],['Source B',c.source_b],['Value B',c.observed_b],['Severity',c.severity],['Status',c.review_status],['Explanation',c.description],['Recommended next evidence',c.nextEvidence],['Human review required',c.requiresHumanReview]])}<h4>Actual conflict evidence</h4>${c.evidence.map(e=>`<details><summary>${esc(e.id)} · ${esc(e.role)}</summary>${kv([['Evidence type',e.evidenceType],['Evidence ID',e.evidenceId],['Observation',e.observationId],['Source',e.sourceType],['Geometry',e.geometryId],['Attribute',e.attribute],['Value',e.value],['Temporal role',e.temporalRole],['Relationship',e.relation],['Notes',e.notes]])}</details>`).join('')||'<p>No evidence rows supplied.</p>'}${c.id===selectedConflict?link('reconciliation','Open Reconciliation'):''}</details>`).join('')||'<p>No conflict records supplied for this parcel.</p>'}${renderDecisionSupport(pid)}</section>`;}
 function setSelection(id){if(!model.parcels.has(id))return false;city.focus(id);return true;}
 function selectConflict(id){const c=model.conflicts.get(id);if(!c)return false;if(!allowed())temporal.setMode('current');if(selected!==c.parcel_id)setSelection(c.parcel_id);selectedConflict=id;selectedEdge=null;chosen.clear();const detail=derived.conflictDetails.find(r=>r.id===id);if(/geometry|boundary|footprint|occupation|area/.test(detail?.attributeOrGeometry||''))for(const oid of c.observationIds||[])if(model.comparison(selected,oid))chosen.add(oid);showConflicts=true;document.querySelector('#showConflictMarkers').checked=true;redraw();api().openTab('conflicts');return true;}
 function selectEdge(id){const edge=model.edges.get(id);if(!edge)return false;if(!allowed())temporal.setMode('current');if(!edge.parcelIds.includes(selected))setSelection(edge.parcelIds[0]);selectedEdge=id;selectedConflict=null;showEdges=true;document.querySelector('#sharedEdges').checked=true;redraw();api().openTab('sources');return true;}
 function selectObservation(id,on=true){if(!model.sources(selected).some(o=>o.id===id&&o.geometry))return false;if(on)chosen.add(id);else chosen.delete(id);redraw();return true;}
 function redraw(){if(disposed)return;const visible=new Set(city.getVisibleCellIds()),matches=model.filtered({type,status,cell}),issueIds=new Set(matches.map(c=>c.parcel_id));const active=allowed();fabric.setIssueIds(active&&issuesOnly?issueIds:null);
  const sourceRows=[],seen=new Set();if(!flatMode){for(const [pid] of model.parcels){if(scope==='selected'&&pid!==selected)continue;if(scope==='cells'&&!visible.has(model.parcels.get(pid).cellId))continue;for(const o of model.sources(pid)){const family=model.families.find(f=>f.sourceType===o.sourceType);if(o.geometry&&layers.includes(family.id)){sourceRows.push({...o,parcelId:pid,color:family.color});seen.add(pid+'|'+o.id);}}}}
  for(const o of model.sources(selected).filter(o=>chosen.has(o.id)&&o.geometry)){if(!seen.has(selected+'|'+o.id))sourceRows.push({...o,parcelId:selected,color:model.families.find(f=>f.sourceType===o.sourceType).color});}
  const comparisons=[...chosen].map(id=>model.comparison(selected,id)).filter(Boolean),edges=showEdges?[...model.edges.values()].filter(e=>e.parcelIds.some(id=>visible.has(model.parcels.get(id).cellId))&&(!selected||e.parcelIds.includes(selected))):[];
  const drawKey=JSON.stringify([sourceRows.map(o=>o.parcelId+'|'+o.id),selected,[...chosen],edges.map(e=>e.id),selectedEdge]);if(drawKey!==lastDrawKey){lastDrawKey=drawKey;renderer.draw({sources:sourceRows,comparisons,sharedEdges:edges,selectedEdge:model.edges.get(selectedEdge)});}
  const grouped=new Map();for(const c of matches){const p=model.parcels.get(c.parcel_id);if(!p?.geometry||!visible.has(p.cellId))continue;if(!p.is_active&&temporal.getState().mode!=='combined')continue;if(!grouped.has(p.id))grouped.set(p.id,[]);grouped.get(p.id).push(c.id);}
  const issueKey=JSON.stringify([showConflicts||issuesOnly,[...grouped]]);if(issueKey!==lastIssueKey){lastIssueKey=issueKey;renderer.drawIssues(showConflicts||issuesOnly?[...grouped].map(([parcelId,ids])=>{const p=model.parcels.get(parcelId),point=model.centroids.get(parcelId)||p.geometry.coordinates[0][0];return {parcelId,ids,point};}):[]);}
  document.getElementById('railConflictCount').textContent=matches.length;
  document.querySelector('#issueSummary').textContent=`${matches.length} matching conflicts · ${issueIds.size} parcels · ${grouped.size} matching parcels in visible cells${active?'':' · suspended in historical/event view'}`;
  legend.hidden=!sourceRows.length&&!comparisons.length&&!showEdges&&!issuesOnly&&!showConflicts;legend.textContent=active?`SOURCE OBSERVATIONS: dashed, mixed dates · Visible geometry difference is diagnostic, not a conflict · Amber: reference-only · Blue: observation-only · Pink dots: recorded conflict locations${issuesOnly?' · Context hidden; unaffected parcels subdued':''}`:'Evidence overlays suspended: historical/event views use a different state. Return to current for comparisons.';
  const empty=document.getElementById('filterEmptyState');if(empty){empty.hidden=!(active&&(issuesOnly||showConflicts)&&!matches.length);empty.textContent='No conflicts match these filters. Change the type, status or cell filter.';}update();invalidate();api().refreshPanel();
 }
 function update(){const active=allowed();city.setEvidenceContextVisible?.(active);fabric.setSelectionFillVisible(!active||(!chosen.size&&!selectedEdge));renderer.root.visible=active;renderer.issues.visible=active;const inspecting=active&&(issuesOnly||showConflicts||showEdges||chosen.size>0||layers.some(id=>model.families.some(f=>f.id===id)));if(inspecting){const status=document.querySelector('.city-detail-status');if(status)status.textContent=flatMode?'Cadastral inspection · source and issue overlays active':'Cadastral inspection · Context models hidden; underlying placements preserved';}if(inspecting&&groups)for(const name of ['buildings','trees','parks','props'])if(groups[name])groups[name].visible=false;const signature=city.getVisibleCellIds().join('|');if(signature!==lastCellSignature){lastCellSignature=signature;if(scope==='cells'||showConflicts||issuesOnly||showEdges)queueMicrotask(()=>{if(!disposed)redraw();});}if(active!==lastAllowed){lastAllowed=active;queueMicrotask(()=>{if(!disposed)redraw();});}}
 function onState(e){layers=e.detail.activeOrder;const id=e.detail.selectedParcel;if(id!==selected){selected=id;chosen.clear();selectedConflict=null;selectedEdge=null;city.setSourceScope?.(scope);}redraw();}
 function onFilter(e){cell=e.detail||'';redraw();}window.addEventListener('praman-spatial-state',onState);window.addEventListener('praman-cell-filter',onFilter);
 function onPanel(event){const target=event.target;if(event.type==='change'){if(target.matches('[data-observation]'))selectObservation(target.dataset.observation,target.checked);if(target.matches('[data-edge-select]'))selectEdge(target.value);return;}
  const button=target.closest('button,a');if(!button)return;if(button.dataset.conflict)selectConflict(button.dataset.conflict);if(button.dataset.edgeNeighbour){const id=selectedEdge;setSelection(button.dataset.edgeNeighbour);selectEdge(id);}if(button.dataset.edgeObservation){setSelection(button.dataset.ownerParcel);selectObservation(button.dataset.edgeObservation);api().openTab('sources');}
  if(button.dataset.evidenceNav){const detail={target:button.dataset.evidenceNav,href:button.href,context:context(),returnTo:new URL(button.href).searchParams.get('returnTo')};const handoff=new CustomEvent('praman:spatial:navigate-dashboard',{detail,cancelable:true});if(!window.dispatchEvent(handoff))event.preventDefault();}
 }
 document.querySelector('#issuesOnly').onchange=e=>{issuesOnly=e.target.checked;if(issuesOnly&&!status&&model.statuses.includes('OPEN')){status='OPEN';document.querySelector('#issueStatus').value=status;}redraw();};document.querySelector('#showConflictMarkers').onchange=e=>{showConflicts=e.target.checked;redraw();};document.querySelector('#sharedEdges').onchange=e=>{showEdges=e.target.checked;if(!showEdges)selectedEdge=null;redraw();};document.querySelector('#sourceScope').onchange=e=>{scope=e.target.value;city.setSourceScope?.(scope);redraw();};for(const id of ['issueType','issueStatus'])document.querySelector('#'+id).onchange=()=>{type=document.querySelector('#issueType').value;status=document.querySelector('#issueStatus').value;redraw();};
 const panel=document.getElementById('panelContent');panel.addEventListener('click',onPanel);panel.addEventListener('change',onPanel);
 const boundary=document.getElementById('boundaryModeButton');const openComparison=()=>{if(selected)api().openTab('sources');};boundary.addEventListener('click',openComparison);
 function handleSelection(s){if(!s||!['edge','source','conflict'].includes(s.kind))return false;if(s.kind==='edge')selectEdge(s.id);else if(s.kind==='conflict')selectConflict(s.id);else{if(selected!==s.parcelId)setSelection(s.parcelId);selectObservation(s.id);api().openTab('sources');}return true;}
 function restore(params){const id=params.get('parcelId')||params.get('parcel');if(id&&model.parcels.has(id))setSelection(id);const filter=params.get('cell');if(data.cells.some(c=>c.id===filter))city.setFilter(filter);type=model.types.includes(params.get('issueType'))?params.get('issueType'):'';status=model.statuses.includes(params.get('issueStatus'))?params.get('issueStatus'):'';issuesOnly=params.get('issues')==='1';document.querySelector('#issueType').value=type;document.querySelector('#issueStatus').value=status;document.querySelector('#issuesOnly').checked=issuesOnly;const cid=params.get('conflictId')||params.get('conflict');if(model.conflicts.get(cid)?.parcel_id===selected)selectConflict(cid);for(const oid of (params.get('observationIds')||'').split(','))selectObservation(oid);const sid=params.get('source');if(sid){const family=data.sourceMetadata.find(s=>s.id===sid||s.type===sid);if(family)for(const o of model.sources(selected).filter(o=>o.sourceType===family.type))selectObservation(o.id);}redraw();}
 return {model,renderer,renderSources,renderConflicts,renderDecisionSupport,selectConflict,selectEdge,selectObservation,handleSelection,restore,update,redraw,href,getState:()=>({selected,selectedConflict,selectedEdge,chosen:[...chosen],type,status,cell,issuesOnly,showEdges,showConflicts,scope,allowed:allowed(),...renderer.getState()}),dispose(){disposed=true;renderer.dispose();fabric.setIssueIds(null);fabric.setSelectionFillVisible(true);toolbar.remove();legend.remove();window.removeEventListener('praman-spatial-state',onState);window.removeEventListener('praman-cell-filter',onFilter);panel.removeEventListener('click',onPanel);panel.removeEventListener('change',onPanel);boundary.removeEventListener('click',openComparison);}};
}
