import {createTemporalModel,loadTemporalDetails} from '../data/temporal-model.js';
import {changedEdges,sharedEdges,ringsOf,segmentsOf} from './geometry-utils.js';
const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
export async function createTemporalView({data,city,fabric,groups,interaction,camera,controls,host,invalidate,renderer:providedRenderer=null,fitGeometry=null,contextEnabled=true}){
 const model=createTemporalModel(data,await loadTemporalDetails());
 if(!providedRenderer)throw new Error('Temporal renderer is required');
 const renderer=providedRenderer;
 const originalFocus=city.focus;
 let mode='current',point='current',selected=null,eventId=null,phase=0,playing=false,raf=0,start=0,plan=null,filter=null,canonical=true,contextOverride=false,lastPhase=-1,disposed=false;
 const bar=el('div',undefined,'temporal-bar');bar.innerHTML='<label>State <select id="temporalMode"><option value="current">Current authoritative</option><option value="historical">Historical / superseded</option><option value="combined">Current + historical</option><option value="proposed">Proposed / review</option></select></label><label>Time machine <select id="temporalPoint"><option value="current">Current authoritative snapshot</option><option value="before">Before first recorded event</option></select></label><label class="temporal-rejected"><input id="temporalRejected" type="checkbox"> Include rejected comparisons</label><button id="temporalReturn" type="button" hidden>Return to current</button>';
 document.querySelector('.city-search-bar').after(bar);const modeSelect=bar.querySelector('#temporalMode'),pointSelect=bar.querySelector('#temporalPoint');
 for(const date of model.points){const option=el('option',date+' · recorded events/versions');option.value=date;pointSelect.append(option);}
 const badge=el('div',undefined,'temporal-badge');badge.setAttribute('role','status');host.append(badge);
 const pane=el('section',undefined,'temporal-panel');pane.innerHTML='<h3>Lifecycle & time</h3><div id="temporalSelection">Select a parcel to inspect its lifecycle.</div><div id="temporalLineage"></div><label id="temporalEventLabel" hidden>Recorded event / version (all dates) <select id="temporalEvent"></select></label><div id="temporalEventInfo"></div><div id="temporalPlayback" hidden><button id="temporalPrevious" type="button">Previous</button><button id="temporalPlay" type="button">Play</button><button id="temporalNext" type="button">Next</button><button id="temporalReplay" type="button">Replay</button><button id="temporalStop" type="button">Exit playback</button></div><p id="temporalPhase"></p><label id="temporalContextLabel" hidden><input id="temporalContext" type="checkbox"> Show current context</label><a id="temporalHistory" hidden>View Parcel History</a>';
 document.querySelector('.layer-sidebar').prepend(pane);
 const eventSelect=pane.querySelector('#temporalEvent'),info=pane.querySelector('#temporalEventInfo'),phaseText=pane.querySelector('#temporalPhase');
 function currentShown(){return point==='current'&&(!plan||plan.type==='record')&&['current','combined','proposed'].includes(mode);}
 function contextShown(){return contextEnabled&&((currentShown()&&mode==='current'&&!plan)||contextOverride);}
 const row=(id,g,style,category)=>({id,geometryId:g.id,geometry:g.geometry,style,category});
 function regularRows(){const rows=[];if(point!=='current'){const snapshot=model.reconstruct(point);for(const r of snapshot.rows)if(r.state==='ACTIVE AT DATE'&&r.geometry)rows.push({...r,style:'snapshot',category:'HISTORICAL RECONSTRUCTION'});return rows;}
  if(['historical','combined'].includes(mode))for(const g of model.geometries.values())if(model.geometryCategory(g)==='HISTORICAL / SUPERSEDED'&&g.geometry)rows.push(row(g.parcelId,g,'historical','HISTORICAL / SUPERSEDED'));
  if(mode==='proposed')for(const g of model.geometries.values()){const category=model.geometryCategory(g);if(['PROPOSED','UNDER REVIEW'].includes(category)||category==='REJECTED'&&bar.querySelector('#temporalRejected').checked)rows.push(row(g.parcelId,g,category==='REJECTED'?'rejected':category==='UNDER REVIEW'?'review':'proposed',category));}
  return rows;
 }
 function filtered(rows){return rows.filter(r=>!filter||model.parcels.get(r.id)?.cellId===filter);}
 function refresh(){if(plan)return renderPhase();const rows=filtered(regularRows());renderer.draw(rows,[],selected);const snapshot=point!=='current'?model.reconstruct(point):null;badge.hidden=point==='current'&&mode==='current';badge.textContent=snapshot?`HISTORICAL RECONSTRUCTION · ${snapshot.date} (end of day) · Locality totals: ${snapshot.counts.active} active · ${snapshot.counts.superseded} superseded · ${snapshot.counts.notYet} not yet existent · ${snapshot.counts.missingGeometry} without dated geometry`:mode==='combined'?'Current authoritative fabric + dashed purple historical versions':mode==='proposed'?'PROPOSED: amber dashed · UNDER REVIEW: orange short dashes · REJECTED: red dashed. None replaces current authority.':'Dashed purple: historical / superseded geometry only';
  if(mode==='proposed'&&point==='current'&&!rows.length)badge.textContent='No proposed or review geometry in this scope. Current authoritative fabric remains visible.';
  bar.querySelector('#temporalReturn').hidden=point==='current'&&mode==='current';pane.querySelector('#temporalContextLabel').hidden=contextShown()&&!contextOverride;update();invalidate();notify();
 }
 function notify(){window.dispatchEvent(new CustomEvent('praman-temporal-state',{detail:{mode,point,playback:plan?.event.id||null,current:currentShown(),selected,snapshot:point==='current'?null:model.reconstruct(point).rows.find(r=>r.id===selected)}}));}
 function update(){
  bar.querySelector('.temporal-rejected').hidden=mode!=='proposed'||point!=='current'||!!plan;
  modeSelect.disabled=!!plan||point!=='current';pointSelect.disabled=!!plan;
  document.querySelector('#conflictCounter').textContent=plan?'Event playback':point!=='current'?'Historical reconstruction':mode==='current'?'CURRENT / AUTHORITATIVE':mode==='combined'?'Current + historical':mode==='proposed'?'Proposed / review':'Historical versions';
  document.querySelector('#datasetFooterSummary').textContent=`Stored dataset: ${data.parcels.length} current · ${data.historicalParcels.length} historical records`;
  document.querySelector('#mapStatusText').textContent=plan?`Event ${plan.event.id} · ${plan.event.date}`:point!=='current'?`Reconstructed at ${point} · local metres`:mode==='current'?`${data.parcels.filter(model.currentAuthority).length} authoritative parcels · ${data.cells.length} cells · metres`:mode==='historical'?'Historical versions · dashed purple · not current authority':mode==='proposed'?'Proposed / rejected comparison over current authority':'Current authority + ghosted historical versions';
  if(fabric.setCanonicalVisible)fabric.setCanonicalVisible(canonical&&currentShown());else if(groups?.parcels)groups.parcels.visible=canonical&&currentShown();
  if(groups)for(const key of ['buildings','trees','parks','props'])if(groups[key])groups[key].visible=canonical&&contextShown();
  renderer.root.visible=true;city.setDetailEnabled?.(contextShown());const labels=host.querySelectorAll('.cell-label,.map-id-label');if(!currentShown())labels.forEach(e=>{e.hidden=true;});}
 function pause(){playing=false;cancelAnimationFrame(raf);pane.querySelector('#temporalPlay').textContent='Play';}
 function exitPlayback(redraw=true){pause();plan=null;phase=0;lastPhase=-1;phaseText.textContent='';if(redraw)refresh();}
 function setMode(value){if(!['current','historical','combined','proposed'].includes(value))throw new Error('Unknown temporal mode');exitPlayback(false);mode=value;point='current';pointSelect.value='current';modeSelect.value=value;contextOverride=false;pane.querySelector('#temporalContext').checked=false;refresh();}
 function setPoint(value){if(value!=='before'&&value!=='current'&&!model.points.includes(value))throw new Error('Choose a recorded point');exitPlayback(false);point=value;mode=value==='current'?'current':'historical';modeSelect.value=mode;pointSelect.value=value;contextOverride=false;pane.querySelector('#temporalContext').checked=false;refresh();renderSelection();fabric.fit();}
 function selectEvent(id){pause();eventId=id;eventSelect.value=id;const e=model.eventById.get(id);info.replaceChildren();if(!e){pane.querySelector('#temporalPlayback').hidden=true;return;}
  const fields=[['Record',e.recordIds.join(', ')],['Table',e.table],['Type',e.type],['Date / timestamp',e.date],['Version',`${e.previousVersion||'not supplied'} → ${e.resultingVersion||'not supplied'}`],['Source',e.source||'not supplied'],['Authority / review',e.authority||'not supplied'],['Actor',e.actor||'not supplied'],['Reason',e.reason||'not supplied']];for(const [key,value] of fields){const p=el('p');p.append(el('strong',key+': '),document.createTextNode(value));info.append(p);}
  if(point!=='current'&&e.day>point)info.append(el('p','This event is later than the reconstructed point and has not been applied to that map.'));
  if(e.geometryComparison)info.append(el('p',`Parent/result union difference: ${e.geometryComparison.symmetricDifferenceSqm.toFixed(3)} m². Stored shapes remain unchanged; accepted lineage does not prove geometric consistency.`));
  if(e.geoGitReference)info.append(el('p','GeoGit reference: '+e.geoGitReference.eventId));const p=model.playback(id);pane.querySelector('#temporalPlayback').hidden=!p||p.type==='unavailable';if(p?.type==='unavailable')info.append(el('p',p.reason));if(p?.type==='record')info.append(el('p',p.reason));
  const link=pane.querySelector('#temporalHistory');link.href=model.historyURL(selected,id,e.resultingVersion);link.hidden=false;if(plan){plan=null;refresh();}notify();
 }
 function renderSelection(){const s=model.selected(selected),box=pane.querySelector('#temporalSelection'),lineage=pane.querySelector('#temporalLineage');box.replaceChildren();lineage.replaceChildren();eventSelect.replaceChildren();pane.querySelector('#temporalEventLabel').hidden=!s?.events.length;
  if(!s){box.textContent='Select a parcel to inspect its lifecycle.';info.replaceChildren();pane.querySelector('#temporalPlayback').hidden=true;pane.querySelector('#temporalHistory').hidden=true;return;}
  box.append(el('strong',s.parcel.id),el('p','Stored category: '+s.category),el('p',`Created: ${s.lifecycle.birth||'unknown'} · Retired: ${s.lifecycle.retired||'not retired'}`),el('p',`Stored record version: ${s.stateVersion||'not supplied'} · Authoritative version field: ${s.authoritativeVersion||'not supplied'}`),el('p',`Stored review status: ${s.review||'not supplied'}`));
  if(point!=='current'){const at=model.reconstruct(point).rows.find(r=>r.id===selected);box.append(el('p',`At ${point}: ${at.state} · record ${at.recordVersion||'unknown'} · geometry ${at.geometryId||'not available'}`));}
  for(const [title,ids] of [['Parents',s.lineage.parents],['Selected parcel',[selected]],['Children / successors',s.lineage.children]]){lineage.append(el('h4',title));if(!ids.length)lineage.append(el('p','None recorded'));for(const id of ids){const b=el('button',id);b.type='button';b.onclick=()=>focus(id);lineage.append(b);}if(title!=='Children / successors')lineage.append(el('span','↓','lineage-arrow'));}
  for(const e of s.events){const option=el('option',`${e.date} · ${e.type} · ${e.id}`);option.value=e.id;eventSelect.append(option);}
  const preferred=s.events.find(e=>e.kind==='lineage')||s.events.find(e=>e.type==='BOUNDARY_CORRECTION')||s.events.at(-1);selectEvent(s.events.some(e=>e.id===eventId)?eventId:preferred?.id);const link=pane.querySelector('#temporalHistory');link.hidden=false;link.href=model.historyURL(selected,eventId,model.eventById.get(eventId)?.resultingVersion);
 }
 function fitRows(rows){if(fitGeometry)return fitGeometry(rows.map(r=>r.geometry||r.g?.geometry).filter(Boolean));const points=rows.flatMap(r=>ringsOf(r.geometry||r.g?.geometry).flat());if(!points.length||!camera||!controls)return;const xs=points.map(p=>p[0]),zs=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),cx=(minX+maxX)/2,cz=(minZ+maxZ)/2,dist=Math.max(90,Math.hypot(maxX-minX,maxZ-minZ)*1.5);controls.target.set?.(cx,0,cz);camera.position.set(cx,dist,cz+dist*.6);controls.update();}
 function beginPlayback(id=eventId){pause();const p=model.playback(id);if(!p||p.type==='unavailable')return false;plan=p;phase=0;lastPhase=-1;city.clearHistoricalFocus();city.setFilter(null);filter=null;fitRows([...(p.before||[]),...(p.after||[])]);renderPhase();return true;}
 function renderPhase(){if(!plan)return;const rows=[],p=plan;let edges=[];const before=()=>p.before.map(r=>row(r.id,r.g,'before','EVENT PREVIOUS GEOMETRY')),after=()=>p.after.map(r=>row(r.id,r.g,p.type==='boundary'&&p.after[0].g.acceptedStatus!=='ACCEPTED'?(p.after[0].g.status==='REJECTED'?'rejected':model.geometryCategory(p.after[0].g)==='UNDER REVIEW'?'review':'proposed'):'after',p.type==='boundary'?model.geometryCategory(p.after[0].g):'ACTIVE AT RECORDED EVENT — NOT CURRENT SNAPSHOT'));
  if(p.type==='split'){if(phase<3)rows.push(...before());if(phase>=2)rows.push(...after());if(phase===1){edges=sharedEdges(p.after.map(r=>r.g.geometry));if(!edges.length)edges=p.after.flatMap(r=>segmentsOf(r.g.geometry));}}
  if(p.type==='merge'){if(phase<3)rows.push(...before());if(phase===1)edges=sharedEdges(p.before.map(r=>r.g.geometry));if(phase===2||phase===3)rows.push(...after());if(phase===2)rows.splice(0,p.before.length);}
  if(p.type==='boundary'){if(phase<2||p.after[0].g.acceptedStatus!=='ACCEPTED')rows.push(...before());if(phase>=1)rows.push(...after());if(phase===1)edges=changedEdges(p.before[0].g.geometry,p.after[0].g.geometry).next;}
  renderer.draw(rows,edges,selected);badge.hidden=false;badge.textContent=`EVENT PLAYBACK · ${p.event.id} · ${p.event.date} · ${p.event.authority||'authority not supplied'} · ${p.type==='record'?'Record-only; no spatial change asserted':'Recorded geometry; current authority remains separate'}`;
  if(p.event.geometryComparison)badge.textContent+=` · Parent/result union difference ${p.event.geometryComparison.symmetricDifferenceSqm.toFixed(3)} m²`;
  phaseText.textContent=`${phase+1}/${p.steps.length} · ${p.steps[phase]}${p.type==='merge'&&phase===1&&!edges.length?' · No shared edge exists in the stored parent geometries.':''}`;pane.querySelector('#temporalContextLabel').hidden=!contextEnabled;bar.querySelector('#temporalReturn').hidden=false;lastPhase=phase;update();invalidate();notify();
 }
 function step(delta){pause();if(!plan&&!beginPlayback())return;phase=Math.max(0,Math.min(plan.steps.length-1,phase+delta));renderPhase();}
 function play(){if(playing){pause();return;}if(!plan&&!beginPlayback())return;if(phase===plan.steps.length-1)phase=0;playing=true;start=performance.now()-phase*1200;pane.querySelector('#temporalPlay').textContent='Pause';const tick=now=>{if(!playing||disposed)return;const elapsed=(now-start)/1200,next=Math.min(plan.steps.length-1,Math.floor(elapsed));if(next!==phase||lastPhase!==next){phase=next;renderPhase();}renderer.animate(elapsed%1,{fade:plan.type==='split'&&phase===2,reveal:phase===1});invalidate();if(elapsed>=plan.steps.length){renderer.animate(1);pause();return;}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);}
 function focus(id){const p=model.parcels.get(id);if(!p)return false;exitPlayback(false);city.clearHistoricalFocus();if(!p.is_active&&point==='current'){mode='combined';modeSelect.value=mode;}refresh();const ok=originalFocus(id);city.clearHistoricalFocus();if(point!=='current'){const r=model.reconstruct(point).rows.find(r=>r.id===id);if(r?.geometry)fitRows([r]);}return ok;}
 const onState=e=>{canonical=e.detail.activeOrder.includes('canonical');if(selected!==e.detail.selectedParcel){pause();plan=null;selected=e.detail.selectedParcel;if(selected&&document.activeElement!==document.querySelector('#citySearch'))document.querySelector('#citySearch').value=selected;renderSelection();refresh();}update();};window.addEventListener('praman-spatial-state',onState);
 const onFilter=e=>{filter=e.detail;refresh();};window.addEventListener('praman-cell-filter',onFilter);
 modeSelect.onchange=()=>setMode(modeSelect.value);pointSelect.onchange=()=>setPoint(pointSelect.value);bar.querySelector('#temporalRejected').onchange=refresh;bar.querySelector('#temporalReturn').onclick=()=>setMode('current');eventSelect.onchange=()=>selectEvent(eventSelect.value);
 pane.querySelector('#temporalPrevious').onclick=()=>step(-1);pane.querySelector('#temporalNext').onclick=()=>step(1);pane.querySelector('#temporalPlay').onclick=play;pane.querySelector('#temporalReplay').onclick=()=>{beginPlayback();play();};pane.querySelector('#temporalStop').onclick=()=>exitPlayback();pane.querySelector('#temporalContext').onchange=e=>{contextOverride=e.target.checked;refresh();};
 city.focus=focus;refresh();return {model,renderer,focus,setMode,setPoint,selectEvent,beginPlayback,step,play,pause,exitPlayback,update,getVisibleParcelIds:()=>[...new Set([...(canonical&&currentShown()?[...fabric.parcelObjects].filter(([,p])=>fabric.cellGroups.get(p.cellId)?.visible).map(([id])=>id):[]),...renderer.records.map(r=>r.id)])],getState:()=>({mode,point,selected,eventId,phase,playing,emphasizedEdges:renderer.emphasizedEdges,playback:plan?.event.id||null,currentShown:currentShown(),contextShown:contextShown(),visibleRecords:renderer.records.map(r=>({id:r.id,geometryId:r.geometryId,category:r.category,style:r.style})),snapshot:point==='current'?null:model.reconstruct(point).counts}),dispose(){disposed=true;city.focus=originalFocus;pause();renderer.dispose();bar.remove();pane.remove();badge.remove();window.removeEventListener('praman-spatial-state',onState);window.removeEventListener('praman-cell-filter',onFilter);}};
}
