const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const root=path.resolve(__dirname,'..'),manifest=JSON.parse(fs.readFileSync(path.join(root,'data/city/manifest.json'))),browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox',...(process.env.PRAMAN_SOFTWARE_GPU?['--no-zygote','--in-process-gpu','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[])]});
 try{
 const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));
 await page.goto(process.env.PRAMAN_TEST_URL);await page.waitForFunction(()=>window.PRAMAN_MAP?.city&&window.PRAMAN_SPATIAL_VIEW.getState().rendererReady);await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());
 const overview=await page.evaluate(()=>window.PRAMAN_MAP.diagnostics());assert.equal(overview.city.activeParcelsStored,manifest.summary.activeParcels);assert.equal(overview.city.activeParcelsVisible,manifest.summary.activeParcels);assert.equal(overview.city.storedHistorical,manifest.historicalRecords);assert.equal(overview.city.planRequests,manifest.cells.length);assert(overview.drawCalls<100);assert.equal(overview.templateLoads,0);
 const identityAudit=await page.evaluate(()=>{const m=window.PRAMAN_MAP,byId=new Map(m.data.parcels.map(p=>[p.id,p])),ids=new Set();let mismatches=0;for(const [cellId,root] of m.fabric.cellGroups)for(const mesh of root.children){if(!mesh.userData.selectionForFace)continue;const positions=mesh.geometry.attributes.position;for(let face=0;face<positions.count/3;face++){const selection=mesh.userData.selectionForFace(face),p=byId.get(selection.id);ids.add(selection.id);if(p.cellId!==cellId)mismatches++;const points=p.geometry.type==='Polygon'?p.geometry.coordinates.flat():p.geometry.coordinates.flat(2);for(let k=0;k<3;k++){const x=positions.getX(face*3+k),z=positions.getZ(face*3+k);if(!points.some(([sx,sz])=>Math.abs(x-sx)<.0002&&Math.abs(z-sz)<.0002))mismatches++;}}}return {identities:ids.size,mismatches};});assert.equal(identityAudit.identities,manifest.summary.activeParcels);assert.equal(identityAudit.mismatches,0);
 const overviewFrames=await page.evaluate(async()=>{const m=window.PRAMAN_MAP,times=[];for(let i=0;i<25;i++){const start=performance.now();m.camera.position.x+=.05;m.controls.update();m.invalidate();await new Promise(requestAnimationFrame);if(i>=5)times.push(performance.now()-start);}times.sort((a,b)=>a-b);return {medianMs:times[10],p95Ms:times[19]};});
 await page.screenshot({path:path.join(root,'docs/stage6-locality.png'),fullPage:true});
 const search=await page.evaluate(()=>{const m=window.PRAMAN_MAP,results={};for(const q of ['IN-DL-110054-3-1','IN-DL-110054-1-101','REV-01-001-01','SRC-A-REV','K-01/1','CELL-04'])results[q]=m.search.search(q).length;return {results,keys:m.search.supportedKeys};});for(const n of Object.values(search.results))assert(n>0);
 await page.fill('#citySearch','K-01/1');await page.waitForSelector('#citySearchResults button');assert(await page.locator('#citySearchResults button').count()<=30);await page.locator('#citySearchResults button').first().click();await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());
 assert.notEqual(await page.locator('#railSelectedParcel').textContent(),'None');await page.locator('#openSelectedButton').click();const layout=await page.evaluate(()=>{const panel=document.querySelector('#parcelPanel').getBoundingClientRect(),map=document.querySelector('.map-frame').getBoundingClientRect(),bar=document.querySelector('.city-search-bar').getBoundingClientRect();return {panelRight:panel.right,mapLeft:map.left,barRight:bar.right,width:innerWidth};});assert(layout.mapLeft>=layout.panelRight-1);assert(layout.barRight<=layout.width);await page.keyboard.press('Escape');
 const samples=[];for(const cell of manifest.cells){await page.evaluate(()=>document.getElementById('filtersMenu').open=true);await page.selectOption('#cityCell',cell.id);await page.evaluate(()=>document.getElementById('filtersMenu').open=false);await page.evaluate(id=>{const m=window.PRAMAN_MAP,c=m.data.cells.find(c=>c.id===id),cx=(c.bounds[0]+c.bounds[2])/2,cz=(c.bounds[1]+c.bounds[3])/2;const p=m.data.parcels.filter(p=>p.cellId===id).sort((a,b)=>{const dist=p=>{const r=p.geometry.coordinates[0];return Math.hypot(r[0][0]-cx,r[0][1]-cz);};return dist(a)-dist(b);})[0];m.city.focus(p.id);},cell.id);await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());await page.waitForFunction(()=>window.PRAMAN_MAP.cells.pending.size===0);const r=await page.evaluate(()=>window.PRAMAN_MAP.diagnostics());assert.deepEqual(r.city.loadErrors,[]);assert.equal(r.city.activeParcelsVisible,manifest.cells.find(c=>c.id===r.city.filter).summary.activeParcels);assert.equal(r.city.loadedCells.length,1);samples.push({cellId:cell.id,...r});}
 const detail=await page.evaluate(async()=>{
  // Synchronize camera matrices before projecting test points after asynchronous cell loading.
  const m=window.PRAMAN_MAP;m.camera.updateMatrixWorld(true);const T=await import('three'),loaded=[...m.cells.loaded.values()][0],parcel=m.data.parcels.find(p=>p.id===window.PRAMAN_SPATIAL_VIEW.getState().selectedParcel),p=parcel.geometry.coordinates[0],center=new T.Box3().setFromPoints(p.map(([x,z])=>new T.Vector3(x,.02,z))).getCenter(new T.Vector3()),rect=m.interaction.canvas.getBoundingClientRect(),v=center.clone().project(m.camera),hit=m.interaction.pick(rect.left+(v.x+1)*rect.width/2,rect.top+(1-v.y)*rect.height/2,'parcel');
  let buildingHit=null;for(const item of loaded.plan.placements.filter(p=>p.kind==='building'&&p.assetId)){const v=new T.Vector3(item.position[0],item.height/2,item.position[2]).project(m.camera),hit=m.interaction.pick(rect.left+(v.x+1)*rect.width/2,rect.top+(1-v.y)*rect.height/2,'building');if(hit?.id===item.id&&!hit.representation){buildingHit=hit;break;}}
  const times=[];for(let i=0;i<35;i++){const start=performance.now();m.camera.position.x+=.12;m.controls.update();m.invalidate();await new Promise(requestAnimationFrame);if(i>=5)times.push(performance.now()-start);}times.sort((a,b)=>a-b);
  return {hit:hit?.id,expected:parcel.id,buildingHit,medianFrameMs:times[Math.floor(times.length/2)],p95FrameMs:times[Math.floor(times.length*.95)],labels:[...document.querySelectorAll('.cell-label,.map-id-label')].filter(e=>!e.hidden).length};
 });assert.equal(detail.hit,detail.expected);assert(detail.buildingHit);assert(detail.labels<=11);
 const hoverAudit=await page.evaluate(async()=>{const m=window.PRAMAN_MAP,c=m.interaction.canvas,r=c.getBoundingClientRect(),before=m.interaction.hoverPicks;for(let i=0;i<100;i++)c.dispatchEvent(new PointerEvent('pointermove',{clientX:r.x+r.width/2,clientY:r.y+r.height/2,buttons:0}));await new Promise(r=>setTimeout(r,240));return m.interaction.hoverPicks-before;});assert(hoverAudit>=1&&hoverAudit<=2);
 await page.screenshot({path:path.join(root,'docs/stage6-cell-detail.png'),fullPage:true});
 const batchAudit=await page.evaluate(async()=>{const m=window.PRAMAN_MAP,T=await import('three'),{CityAssets}=await import('./map/city-assets.js'),{ASSET_LIST}=await import('./map/asset-registry.js'),cache=new CityAssets(m.assets);let checked=0;for(const spec of ASSET_LIST.filter(s=>s.instancingAllowed&&m.assets.cache.has(s.url))){const parts=await cache.template(spec.id),box=new T.Box3();for(const part of parts){part.geometry.computeBoundingBox();box.union(part.geometry.boundingBox);}const original=await m.assets.clone(spec.id),exact=new T.Box3();let sourceTriangles=0;original.updateMatrixWorld(true);original.traverse(o=>{if(!o.isMesh)return;const position=o.geometry.attributes.position,index=o.geometry.index,count=index?index.count:position.count;sourceTriangles+=count/3;for(let i=0;i<count;i++)exact.expandByPoint(new T.Vector3().fromBufferAttribute(position,index?index.getX(i):i).applyMatrix4(o.matrixWorld));});const size=box.getSize(new T.Vector3()),triangles=parts.reduce((n,p)=>n+p.geometry.attributes.position.count/3,0);if(box.min.distanceTo(exact.min)>.005||box.max.distanceTo(exact.max)>.005||triangles!==sourceTriangles||size.x>spec.footprintWidth+.005||size.z>spec.footprintDepth+.005||size.y>spec.approxHeight+.005)throw new Error('Batch changed drawn GLB geometry '+spec.id+' '+JSON.stringify({actual:size.toArray(),source:exact.getSize(new T.Vector3()).toArray(),triangles,sourceTriangles}));checked++;}await cache.dispose();return checked;});assert(batchAudit>0);
 await page.evaluate(()=>window.PRAMAN_MAP.city.focus('IN-DL-110054-1-101'));await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());assert.equal(await page.locator('#railSelectedParcel').textContent(),'IN-DL-110054-1-101');assert(await page.evaluate(()=>window.PRAMAN_MAP.groups.historicalGeometry.children.length>0));
 await page.locator('#fitButton').click();await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());const reset=await page.evaluate(()=>window.PRAMAN_MAP.diagnostics());assert.equal(reset.city.loadedCells.length,0);assert.equal(reset.city.activeParcelsVisible,manifest.summary.activeParcels);assert(reset.city.cellUnloads>=manifest.cells.length);
 await page.evaluate(()=>window.PRAMAN_SPATIAL_VIEW.toggleLayer('canonical',false));await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());assert.equal(await page.evaluate(()=>window.PRAMAN_SPATIAL_VIEW.getVisibleParcelIds().length),0);
 assert.deepEqual(errors,[]);const report={overview,overviewFrames,identityAudit,batchAudit,hoverAudit,cells:samples,detail,afterReset:reset,search,layout,errors};fs.writeFileSync(path.join(root,'docs/city-runtime-validation.json'),JSON.stringify(report,null,2));console.log('PASS: full locality, all cell loads/evictions, batching identities, historical/source/Khasra search, cell filters, 1366x768 inspector layout, runtime metrics and no browser errors.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
