const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox',...(process.env.PRAMAN_SOFTWARE_GPU?['--no-zygote','--in-process-gpu','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[])]});try{
 const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error')console.error('BROWSER',m.text());});await page.goto(process.env.PRAMAN_TEST_URL);await page.waitForFunction(()=>window.PRAMAN_MAP?.evidence&&window.PRAMAN_SPATIAL_VIEW.getState().rendererReady);
 const start=await page.evaluate(()=>({active:window.PRAMAN_MAP.fabric.parcelObjects.size,state:window.PRAMAN_MAP.evidence.getState(),model:window.PRAMAN_MAP.evidence.model.derived.summary}));assert.equal(start.state.sourceObservationIds.length,0);assert.equal(start.state.selectedConflict,null);
 const target=await page.evaluate(()=>{const e=window.PRAMAN_MAP.evidence,p=e.model.data.parcels.find(p=>e.model.sources(p.id).length>=3&&e.model.conflictsFor(p.id).some(c=>c.type==='SHIFTED_GEOMETRY'));window.PRAMAN_MAP.city.focus(p.id);window.PRAMAN_SPATIAL_VIEW.openTab('sources');return {id:p.id,observations:e.model.sources(p.id).slice(0,2).map(o=>o.id)};});
 for(const id of target.observations){await page.locator('details.source-observation').filter({has:page.locator(`[data-observation="${id}"]`)}).locator('summary').first().click();await page.check(`[data-observation="${id}"]`);}let s=await page.evaluate(()=>window.PRAMAN_MAP.evidence.getState());assert.deepEqual(s.chosen,target.observations);assert.deepEqual(s.comparisonObservationIds,target.observations);assert((await page.locator('#panelContent').textContent()).includes('Measured geometry comparison'));assert.equal(await page.locator('#boundaryModeButton').isDisabled(),false);
 const pickSource=await page.evaluate(async()=>{const m=window.PRAMAN_MAP,T=await import('three'),mesh=m.evidence.renderer.root.children.find(o=>o.isMesh),pos=mesh.geometry.attributes.position,point=new T.Vector3();for(let i=0;i<3;i++)point.add(new T.Vector3().fromBufferAttribute(pos,i));point.multiplyScalar(1/3);mesh.updateWorldMatrix(true,false);point.applyMatrix4(mesh.matrixWorld);const v=point.project(m.camera),r=m.interaction.canvas.getBoundingClientRect();return m.interaction.pick(r.x+(v.x+1)*r.width/2,r.y+(1-v.y)*r.height/2,'source');});assert.equal(pickSource.kind,'source');assert.equal(pickSource.parcelId,target.id);
 await page.screenshot({path:path.resolve(__dirname,'../docs/stage8-source-comparison.png'),fullPage:true});
 await page.evaluate(()=>window.PRAMAN_SPATIAL_VIEW.openTab('evidence'));await page.locator('.why-match summary').first().click();assert((await page.locator('#panelContent').textContent()).includes('Reconciliation confidence'));assert((await page.locator('#panelContent').textContent()).includes('Identifier confidence'));assert(!(await page.locator('#panelContent').textContent()).includes('AI score'));
 const edge=await page.evaluate(()=>{const m=window.PRAMAN_MAP,e=m.evidence,edge=[...e.model.edges.values()].find(e=>e.parcelIds.some(id=>m.evidence.model.conflictsFor(id).length));e.selectEdge(edge.id);return {id:edge.id,pids:edge.parcelIds};});assert((await page.locator('#panelContent').textContent()).includes('one boundary record for both neighbours'));await page.locator(`[data-edge-neighbour="${edge.pids[1]}"]`).click();assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.evidence.getState().selectedEdge),edge.id);
 const pickEdge=await page.evaluate(async()=>{const m=window.PRAMAN_MAP,T=await import('three'),e=m.evidence.model.edges.get(m.evidence.getState().selectedEdge),line=e.lines[0],a=line[0],b=line[1],point=new T.Vector3((a[0]+b[0])/2,.34,(a[1]+b[1])/2),v=point.project(m.camera),r=m.interaction.canvas.getBoundingClientRect();return m.interaction.pick(r.x+(v.x+1)*r.width/2,r.y+(1-v.y)*r.height/2,'edge');});assert.equal(pickEdge.id,edge.id);
 await page.screenshot({path:path.resolve(__dirname,'../docs/stage8-shared-edge.png'),fullPage:true});
 const owner=await page.evaluate(()=>{const e=window.PRAMAN_MAP.evidence,c=[...e.model.conflicts.values()].find(c=>c.type==='OWNERSHIP_DISAGREEMENT');e.selectConflict(c.id);return {id:c.id,parcelId:c.parcel_id};});assert((await page.locator('#panelContent').textContent()).includes(owner.id));assert.equal((await page.evaluate(()=>window.PRAMAN_MAP.evidence.getState())).comparisonObservationIds.length,0);assert((await page.locator('#panelContent').textContent()).includes('Actual conflict evidence'));
 await page.locator('#closePanelButton').click();await page.locator('#issuesMenu summary').click();await page.check('#issuesOnly');await page.selectOption('#issueType','OWNERSHIP_DISAGREEMENT');await page.selectOption('#issueStatus','OPEN');const issues=await page.evaluate(()=>{const m=window.PRAMAN_MAP,e=m.evidence,expected=e.model.filtered({type:'OWNERSHIP_DISAGREEMENT',status:'OPEN'}),mesh=[...m.fabric.cellGroups.values()].flatMap(g=>g.children).find(o=>o.userData.originalColors),colors=mesh.geometry.attributes.color.array;return {count:expected.length,text:document.getElementById('issueSummary').textContent,subdued:colors.some((v,i)=>Math.abs(v-mesh.userData.originalColors[i])>1e-6),buildings:m.groups.buildings.visible,summary:document.getElementById('railConflictCount').textContent};});assert(issues.text.startsWith(issues.count+' matching'));assert(issues.subdued);assert.equal(issues.buildings,false);assert.equal(Number(issues.summary),issues.count);
 await page.evaluate(()=>window.PRAMAN_MAP.reset());await page.screenshot({path:path.resolve(__dirname,'../docs/stage8-issues-only.png'),fullPage:true});
 const markerPick=await page.evaluate(async()=>{const m=window.PRAMAN_MAP,T=await import('three'),mesh=m.evidence.renderer.issues.children[0],matrix=new T.Matrix4();mesh.getMatrixAt(0,matrix);const point=new T.Vector3().setFromMatrixPosition(matrix),selection=mesh.userData.selectionByInstance[0];m.city.focus(selection.parcelId);await new Promise(requestAnimationFrame);m.groups.conflicts.updateMatrixWorld(true);m.camera.updateMatrixWorld(true);const v=point.project(m.camera),r=m.interaction.canvas.getBoundingClientRect();return m.interaction.pick(r.x+(v.x+1)*r.width/2,r.y+(1-v.y)*r.height/2,'conflict');});assert.equal(markerPick.kind,'conflict');
 await page.locator('#compareMenu summary').click();await page.selectOption('#sourceScope','cells');const familyCoverage=await page.evaluate(()=>{const m=window.PRAMAN_MAP,counts={};for(const f of m.evidence.model.families){window.PRAMAN_SPATIAL_VIEW.toggleLayer(f.id,true);const visible=new Set(m.city.diagnostics().visibleCellIds),expected=m.data.parcels.concat(m.data.historicalParcels).flatMap(p=>visible.has(p.cellId)?m.evidence.model.sources(p.id).filter(o=>o.geometry&&o.sourceType===f.sourceType):[]);const actual=m.evidence.getState().sourceObservationIds;for(const o of expected)if(!actual.includes(o.id))throw Error('Missing family overlay '+o.id);counts[f.sourceType]=expected.length;window.PRAMAN_SPATIAL_VIEW.toggleLayer(f.id,false);}return counts;});assert.equal(Object.keys(familyCoverage).length,7);await page.selectOption('#sourceScope','selected');await page.locator('#compareMenu summary').click();
 // External dashboards remain separate; verify cancelable handoff and exact return context.
 await page.evaluate(()=>{const e=window.PRAMAN_MAP.evidence,c=e.model.filtered({type:'OWNERSHIP_DISAGREEMENT',status:'OPEN'})[0];e.selectConflict(c.id);window.addEventListener('praman:spatial:navigate-dashboard',event=>{event.preventDefault();window.lastEvidenceHandoff=event.detail;});});await page.locator('[data-evidence-nav="reconciliation"]').click();const navigation=await page.evaluate(()=>window.lastEvidenceHandoff);const url=new URL(navigation.href);assert.equal(url.searchParams.get('view'),'reconcile');assert.equal(url.searchParams.get('parcel'),navigation.context.parcelId);assert.equal(url.searchParams.get('conflict'),navigation.context.conflictId);assert(url.searchParams.get('source'));assert(url.searchParams.get('returnTo'));await page.locator('[data-evidence-nav="evidenceGraph"]').click();const graph=await page.evaluate(()=>window.lastEvidenceHandoff);assert.equal(graph.target,'evidenceGraph');assert.equal(new URL(graph.href).searchParams.get('parcel'),navigation.context.parcelId);
 await page.goto(navigation.returnTo);await page.waitForFunction(()=>window.PRAMAN_MAP?.evidence&&window.PRAMAN_SPATIAL_VIEW.getState().rendererReady);s=await page.evaluate(()=>window.PRAMAN_MAP.evidence.getState());assert.equal(s.selectedConflict,navigation.context.conflictId);assert.equal(s.type,navigation.context.type);assert.equal(s.status,navigation.context.status);assert(s.issuesOnly);
 const temporal=await page.evaluate(()=>{const m=window.PRAMAN_MAP;m.temporal.setPoint(m.temporal.model.points[0]);m.evidence.update();return {visible:m.evidence.renderer.root.visible,markers:m.evidence.renderer.issues.visible,authority:m.temporal.getState().currentShown};});assert.equal(temporal.visible,false);assert.equal(temporal.markers,false);assert.equal(temporal.authority,false);await page.evaluate(()=>{window.PRAMAN_MAP.temporal.setMode('current');window.PRAMAN_MAP.evidence.update();});
 const noConflicts=await page.evaluate(()=>{const m=window.PRAMAN_MAP,p=m.data.parcels.find(p=>!m.evidence.model.conflictsFor(p.id).length);m.city.focus(p.id);window.PRAMAN_SPATIAL_VIEW.openTab('conflicts');return p.id;});assert((await page.locator('#panelContent').textContent()).includes('No conflict records supplied'));assert.equal(await page.locator('[data-evidence-nav="reconciliation"]').count(),0);
 const review=await page.evaluate(()=>{const m=window.PRAMAN_MAP,p=m.data.reconciliation.find(r=>r.requiresHumanReview==='True');m.city.focus(p.parcelId);window.PRAMAN_SPATIAL_VIEW.openTab('overview');return p.parcelId;});assert((await page.locator('#panelContent').textContent()).includes('System proposal'));assert((await page.locator('#panelContent').textContent()).includes('CURRENT / AUTHORITATIVE'));const layout=await page.evaluate(()=>{const map=document.querySelector('.map-frame').getBoundingClientRect(),p=document.querySelector('#parcelPanel').getBoundingClientRect();return {mapLeft:map.left,panelRight:p.right,mapHeight:map.height,bodyWidth:document.body.scrollWidth,viewport:innerWidth};});assert(layout.mapLeft>=layout.panelRight-1);assert(layout.mapHeight>=220);assert(layout.bodyWidth<=layout.viewport);
 assert.deepEqual(errors,[]);const report={markerPick,familyCoverage,start,target,pickSource,edge,pickEdge,owner,issues,navigation,graph,noConflicts,review,layout,errors};fs.writeFileSync(path.resolve(__dirname,'../docs/evidence-runtime-validation.json'),JSON.stringify(report,null,2));console.log('PASS: evidence overlays, multi-source differences, shared-edge identity/picking, ownership vs geometry, issues filters, decision-support fields, existing panels, navigation return context, temporal authority safety, 1366×768 and no page errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
