const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox',...(process.env.PRAMAN_SOFTWARE_GPU?['--no-zygote','--in-process-gpu','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[])]});
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));page.on('request',r=>requests.push(r.url()));
 await page.goto((process.env.PRAMAN_TEST_URL||'http://127.0.0.1:8000/layer2/')+'?mode=calibration');
 await page.waitForFunction(()=>window.PRAMAN_SPATIAL_VIEW?.getState().rendererReady);
 const result=await page.evaluate(async()=>{
  const m=window.PRAMAN_MAP,T=await import('three');
  await m.viewer.show(['buildings-building-10']);
  const baseLoads=m.assets.loads;
  const {createParcel}=await import('./map/parcel-renderer.js');
  const footprint=createParcel({id:'test-independent',outer:[[-18,-18],[18,-18],[18,18],[-18,18]],testOnly:true});m.groups.parcels.add(footprint.object);m.interaction.register(footprint.object);
  const a=await m.assets.clone('buildings-building-10'),b=await m.assets.clone('buildings-building-10');
  let am,bm;a.traverse(o=>{if(o.isMesh&&!am)am=o;});b.traverse(o=>{if(o.isMesh&&!bm)bm=o;});
  const box=new T.Box3().setFromObject(a),size=box.getSize(new T.Vector3());
  const rect=m.interaction.canvas.getBoundingClientRect();
  const screen=point=>{const v=point.clone().project(m.camera);return [rect.left+(v.x+1)*rect.width/2,rect.top+(1-v.y)*rect.height/2];};
  const [x,y]=screen(box.getCenter(new T.Vector3()));
  const building=m.interaction.pick(x,y,'building');
  const [px,py]=screen(new T.Vector3(0,0.02,0));
  const parcel=m.interaction.pick(px,py,'parcel');
  m.groups.buildings.visible=false;const parcelWithoutBuilding=m.interaction.pick(px,py,'parcel');m.groups.buildings.visible=true;
  const placed=await m.assets.instances('buildings-building-10',[{matrix:new T.Matrix4().makeTranslation(0,0,0),selection:{kind:'building',id:'instance-a'}},{matrix:new T.Matrix4().makeTranslation(30,0,0),selection:{kind:'building',id:'instance-b'}}]);
  m.groups.buildings.add(placed);const unregister=m.interaction.register(placed);
  m.groups.buildings.children[0].visible=false;
  const [ix,iy]=screen(box.getCenter(new T.Vector3()).add(new T.Vector3(30,0,0)));
  const instance=m.interaction.pick(ix,iy,'building');
  m.groups.buildings.children[0].visible=true;unregister();placed.removeFromParent();placed.traverse(o=>{if(o.isInstancedMesh)o.dispose();});
  const {CellManager}=await import('./map/city-builder.js');
  const cells=new CellManager();let loads=0,attached=0,released=0;
  cells.register('test',async()=>{loads++;return {attach(){attached++;},dispose(){released++;}};});
  await Promise.all([cells.sync(['test']),cells.sync(['test'])]);await cells.sync([]);cells.dispose();
  const visible=m.index.query(m.camera,1500).includes('buildings-building-10'),hidden=m.index.query(m.camera,1).length===0;
  return {baseLoads,revision:m.diagnostics().threeRevision,groups:m.diagnostics().groups.length,loads:m.assets.loads,reused:am.geometry===bm.geometry&&am.material===bm.material,width:size.x,ground:box.min.y,building:building?.kind,parcel:parcel?.kind,independent:parcelWithoutBuilding?.kind,instance:instance?.id,instanceId:instance?.instanceId,cell:{loads,attached,released},visible,hidden,position:m.camera.position.toArray(),target:m.controls.target.toArray()};
 });
 assert.equal(result.revision,'180');assert.equal(result.groups,10);assert.equal(result.loads,result.baseLoads);assert(result.reused);assert(result.width>0);assert(Math.abs(result.ground)<1e-5);
 assert.equal(result.building,'building');assert.equal(result.parcel,'parcel');assert.equal(result.independent,'parcel');assert.equal(result.instance,'instance-b');assert.equal(result.instanceId,1);assert.deepEqual(result.cell,{loads:1,attached:1,released:1});assert(result.visible&&result.hidden);
 const canvas=page.locator('canvas'),bounds=await canvas.boundingBox(),cx=bounds.x+bounds.width/2,cy=bounds.y+bounds.height/2;
 await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+100,cy+80,{steps:8});await page.mouse.up();
 let position=await page.evaluate(()=>window.PRAMAN_MAP.camera.position.toArray());assert.notDeepEqual(position,result.position);
 await page.mouse.move(cx,cy);await page.mouse.down({button:'right'});await page.mouse.move(cx+60,cy+30,{steps:5});await page.mouse.up({button:'right'});
 assert.notDeepEqual(await page.evaluate(()=>window.PRAMAN_MAP.controls.target.toArray()),result.target);
 await page.mouse.wheel(0,-300);await page.waitForTimeout(100);
 const limits=await page.evaluate(()=>{const c=window.PRAMAN_MAP.controls;return {angle:c.getPolarAngle(),min:c.minPolarAngle,max:c.maxPolarAngle,d:c.getDistance(),minD:c.minDistance,maxD:c.maxDistance};});
 assert(limits.angle>=limits.min&&limits.angle<=limits.max&&limits.d>=limits.minD&&limits.d<=limits.maxD);
 await page.locator('#fitButton').click();assert.deepEqual(await page.evaluate(()=>window.PRAMAN_MAP.camera.position.toArray()),result.position);
 await page.waitForTimeout(100);const frame=await page.evaluate(()=>window.PRAMAN_MAP.diagnostics().renderCount);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.diagnostics().renderCount),frame);
 assert.equal(requests.filter(u=>u.endsWith('building-10.glb')).length,1);assert(requests.every(u=>u.startsWith('http://127.0.0.1')||u.startsWith('blob:')));assert.deepEqual(errors,[]);
 await page.screenshot({path:require('node:path').resolve(__dirname,'../../stage2-verified.png')});
 console.log('PASS: local-only renderer, GLTFLoader, 10 groups, metre calibration, camera orbit/pan/zoom/reset, independent parcel/building and instance picking, template reuse, distance/frustum query, cell lifecycle, idle rendering, zero page errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
