const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--no-zygote','--in-process-gpu','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const page=await browser.newPage(),errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)missing.push(r.url());});page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(process.env.PRAMAN_TEST_URL);await page.waitForFunction(()=>window.PRAMAN_MAP?.ui);const report={screens:[],cases:[],errors,missing};
for(const [width,height] of [[1366,768],[1440,900],[1920,1080]]){await page.setViewportSize({width,height});await page.evaluate(()=>window.PRAMAN_SPATIAL_VIEW.clearSelection());await page.screenshot({path:path.resolve(__dirname,`../docs/final-ui-${width}-overview.png`)});let r=await page.evaluate(()=>{const m=document.querySelector('.map-frame').getBoundingClientRect();return {width:innerWidth,height:innerHeight,mapWidth:m.width,mapHeight:m.height,overflow:document.body.scrollWidth>innerWidth};});assert.equal(r.overflow,false);assert(r.mapWidth>=width-2&&r.mapHeight>=height*.6);
for(const id of ['layersMenu','filtersMenu','issuesMenu','compareMenu','historyMenu']){await page.locator('#'+id+' > summary').click();const b=await page.locator('#'+id+' .workspace-menu-content').boundingBox();assert(b.x>=0&&b.x+b.width<=width&&b.y+b.height<=height);await page.locator('#'+id+' > summary').click();}
await page.evaluate(()=>{window.PRAMAN_MAP.city.focus('IN-DL-110054-1-4');window.PRAMAN_SPATIAL_VIEW.openTab('overview');});await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());await page.screenshot({path:path.resolve(__dirname,`../docs/final-ui-${width}-inspector.png`)});const selected=await page.evaluate(()=>{const p=document.getElementById('parcelPanel').getBoundingClientRect(),m=document.querySelector('.map-frame').getBoundingClientRect();const tiny=[...document.querySelectorAll('body *')].filter(e=>e.children.length===0&&e.textContent.trim()&&e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&parseFloat(getComputedStyle(e).fontSize)<12).map(e=>({tag:e.tagName,text:e.textContent.slice(0,40),font:getComputedStyle(e).fontSize}));return {panelRight:p.right,mapLeft:m.left,mapHeight:m.height,tiny};});assert(selected.mapLeft>=selected.panelRight-1);assert(selected.mapHeight>=400);assert.deepEqual(selected.tiny,[]);r.selected=selected;report.screens.push(r);await page.locator('#closePanelButton').click();}
report.cases=await page.evaluate(()=>{const m=window.PRAMAN_MAP,types=m.city.manifest.propertyTypes,patterns={vacant:/VACANT/,residential:/INDEPENDENT|RESIDENTIAL/,apartment:/APARTMENT|GROUP_HOUSING/,commercial:/COMMERCIAL|SHOP/,government:/GOVERNMENT/,park:/PUBLIC_PARK/},out=[];for(const [kind,re] of Object.entries(patterns)){const id=Object.keys(types).find(id=>re.test(types[id]));if(!id)throw Error('No representative '+kind);m.city.focus(id);window.PRAMAN_SPATIAL_VIEW.openTab('overview');if(window.PRAMAN_SPATIAL_VIEW.getState().selectedParcel!==id)throw Error('Selection failed');out.push({kind,id,type:types[id]});}const counts=new Map();for(const b of m.data.buildingRecords)counts.set(b.parcelId,(counts.get(b.parcelId)||0)+1);const id=[...counts].find(([,n])=>n>1)[0];m.city.focus(id);out.push({kind:'multiple buildings',id,count:counts.get(id)});return out;});
await page.evaluate(()=>{const m=window.PRAMAN_MAP;m.city.focus('IN-DL-110054-1-4');window.PRAMAN_SPATIAL_VIEW.openTab('sources');m.evidence.selectObservation(m.evidence.model.sources('IN-DL-110054-1-4')[0].id);});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.buildings.visible),false);await page.screenshot({path:path.resolve(__dirname,'../docs/final-ui-source-inspection.png')});
await page.evaluate(()=>{const m=window.PRAMAN_MAP;const pair=m.evidence.model.types.flatMap(type=>m.evidence.model.statuses.map(status=>({type,status}))).find(f=>!m.evidence.model.filtered(f).length);document.getElementById('issuesMenu').open=true;for(const [id,v] of [['issueType',pair.type],['issueStatus',pair.status]]){const e=document.getElementById(id);e.value=v;e.dispatchEvent(new Event('change'));}const e=document.getElementById('issuesOnly');e.checked=true;e.dispatchEvent(new Event('change'));});assert(await page.locator('#filterEmptyState').isVisible());
await page.evaluate(()=>{const m=window.PRAMAN_MAP;m.temporal.setMode('combined');m.evidence.update();});assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.buildings.visible),false);
assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);fs.writeFileSync(path.resolve(__dirname,'../docs/FINAL_UI_VALIDATION.json'),JSON.stringify(report,null,2));console.log('PASS: actual responsive views, all toolbar groups, readable text, inspector no overlap, semantic parcel cases, cadastral inspection context and empty filter state.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
