const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox',...(process.env.PRAMAN_SOFTWARE_GPU?['--no-zygote','--in-process-gpu','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[])]});try{const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.PRAMAN_TEST_URL);await page.waitForFunction(()=>window.PRAMAN_MAP?.temporal&&window.PRAMAN_SPATIAL_VIEW.getState().rendererReady);
const baseline=await page.evaluate(()=>{const m=window.PRAMAN_MAP,t=m.temporal;return {state:t.getState(),current:m.fabric.parcelObjects.size,model:t.model.events.length,visible:m.groups.parcels.visible};});assert.equal(baseline.state.mode,'current');assert.equal(baseline.state.point,'current');assert.equal(baseline.state.visibleRecords.length,0);assert(baseline.visible);assert.equal(await page.locator('#temporalPlayback').isVisible(),false);
await page.selectOption('#temporalMode','historical');let s=await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState());assert(s.visibleRecords.length>0);assert(s.visibleRecords.every(r=>r.style==='historical'));assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.parcels.visible),false);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.buildings.visible),false);
await page.selectOption('#temporalMode','combined');assert.equal(await page.evaluate(()=>window.PRAMAN_SPATIAL_VIEW.getVisibleParcelIds().length),await page.evaluate(()=>window.PRAMAN_MAP.data.parcels.length+window.PRAMAN_MAP.data.historicalParcels.length));assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.parcels.visible),true);
await page.selectOption('#temporalMode','proposed');s=await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState());assert(s.visibleRecords.length>0);assert(s.visibleRecords.every(r=>['PROPOSED','UNDER REVIEW'].includes(r.category)));await page.locator('#historyMenu summary').click();await page.check('#temporalRejected');await page.locator('#historyMenu summary').click();s=await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState());assert(s.visibleRecords.some(r=>r.category==='REJECTED'&&r.style==='rejected'));assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.parcels.visible),true);
await page.evaluate(()=>window.PRAMAN_MAP.temporal.setMode('current'));const historical=await page.evaluate(()=>{const m=window.PRAMAN_MAP,id=m.data.historicalParcels[0].id;const hit=m.search.search(id).find(h=>h.id===id);m.search.choose(hit);return id;});assert.equal(await page.locator('#railSelectedParcel').textContent(),historical);assert((await page.locator('#temporalSelection').textContent()).includes('HISTORICAL / SUPERSEDED'));assert(await page.evaluate(()=>window.PRAMAN_MAP.temporal.renderer.selectedGeometryId));assert((await page.locator('#temporalLineage').textContent()).includes('Children / successors'));
const playback=await page.evaluate(()=>{const m=window.PRAMAN_MAP,t=m.temporal,result=[];for(const type of ['SPLIT','MERGE','CROSS_CELL_SPLIT','CROSS_CELL_MERGE']){const e=t.model.transactions.find(e=>e.type===type);t.focus(e.parents[0]);t.selectEvent(e.id);const assertStart=t.beginPlayback(e.id);const phases=[];for(let i=0;i<4;i++){phases.push(t.getState());t.step(1);}result.push({type,started:assertStart,eventId:e.id,phases});t.exitPlayback();}return result;});for(const p of playback){assert(p.started);assert(p.phases[0].visibleRecords.length);assert(p.phases[1].emphasizedEdges>0);assert(p.phases[3].visibleRecords.every(r=>r.style==='after'));assert(p.phases.every(s=>s.currentShown===false));}
const correction=await page.evaluate(()=>{const t=window.PRAMAN_MAP.temporal,g=[...t.model.geometries.values()].find(g=>g.supersedesGeometryId&&g.acceptedStatus==='ACCEPTED');t.focus(g.parcelId);t.selectEvent(g.id);t.beginPlayback(g.id);const old=t.getState();t.step(1);const compare=t.getState();t.step(1);return {old,compare,accepted:t.getState()};});assert.equal(correction.old.visibleRecords[0].style,'before');assert.equal(correction.compare.visibleRecords.length,2);assert(correction.compare.emphasizedEdges>0);assert(correction.accepted.visibleRecords.every(r=>r.style==='after'));
await page.screenshot({path:path.resolve(__dirname,'../docs/stage7-boundary-playback.png'),fullPage:true});
const proposals=await page.evaluate(()=>{const t=window.PRAMAN_MAP.temporal,result=[];for(const status of ['PROPOSED','REJECTED']){const g=[...t.model.geometries.values()].find(g=>g.status===status);t.focus(g.parcelId);t.selectEvent(g.id);t.beginPlayback(g.id);t.step(1);t.step(1);result.push(t.getState());}return result;});for(const s of proposals){assert(s.visibleRecords.some(r=>r.style==='before'));assert(!s.visibleRecords.some(r=>r.style==='after'));}
await page.evaluate(()=>{const t=window.PRAMAN_MAP.temporal,e=t.model.transactions.find(e=>e.type==='SPLIT');t.focus(e.parents[0]);t.selectEvent(e.id);t.beginPlayback(e.id);t.play();});await page.waitForTimeout(500);assert(await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState().playing));await page.evaluate(()=>window.PRAMAN_SPATIAL_VIEW.openTab('lineage'));await page.locator('#temporalPlay').click();assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState().playing),false);await page.locator('#temporalReplay').click();await page.waitForTimeout(5100);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState().phase),3);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState().playing),false);
await page.screenshot({path:path.resolve(__dirname,'../docs/stage7-split-playback.png'),fullPage:true});
const rollback=await page.evaluate(()=>{const t=window.PRAMAN_MAP.temporal,e=t.model.events.find(e=>e.type==='ROLLBACK');t.focus(e.primaryParcelId);t.selectEvent(e.id);t.beginPlayback(e.id);return {state:t.getState(),url:t.model.historyURL(e.primaryParcelId,e.id,e.resultingVersion),id:e.id};});assert.equal(rollback.state.visibleRecords.length,0);assert(rollback.state.currentShown);assert((await page.locator('#temporalEventInfo').textContent()).includes('Record rollback only'));
await page.evaluate(()=>window.PRAMAN_MAP.temporal.setPoint('before'));s=await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState());assert.equal(s.snapshot.active,0);assert.equal(s.visibleRecords.length,0);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.parcels.visible),false);
const reconstruction=await page.evaluate(()=>{const t=window.PRAMAN_MAP.temporal,e=t.model.transactions.find(e=>e.type==='CROSS_CELL_SPLIT');t.setPoint(e.day);return t.getState();});assert(reconstruction.visibleRecords.length>0);assert(reconstruction.visibleRecords.every(r=>r.category==='HISTORICAL RECONSTRUCTION'));assert(reconstruction.snapshot.notYet>0);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.buildings.visible),false);
await page.screenshot({path:path.resolve(__dirname,'../docs/stage7-time-machine.png'),fullPage:true});
assert.equal(await page.locator('#temporalHistory').getAttribute('href'),rollback.url);await page.locator('#temporalHistory').click();await page.waitForFunction(()=>window.PRAMAN_HISTORY?.selected);assert.equal(await page.evaluate(()=>window.PRAMAN_HISTORY.eventId),rollback.id);assert((await page.locator('#historyBack').getAttribute('href')).includes('eventId='+rollback.id));await page.locator('#historyBack').click();await page.waitForFunction(()=>window.PRAMAN_MAP?.temporal&&window.PRAMAN_SPATIAL_VIEW.getState().rendererReady);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState().eventId),rollback.id);
// Independent building transforms survive a boundary playback; showing current buildings is explicit.
await page.evaluate(()=>window.PRAMAN_MAP.city.whenSettled());const independence=await page.evaluate(()=>{const m=window.PRAMAN_MAP,t=m.temporal,objects=[];m.groups.buildings.traverse(o=>{if(o.isMesh)objects.push({o,matrix:o.matrix.toArray(),instances:o.isInstancedMesh?Array.from(o.instanceMatrix.array):null});});const g=[...t.model.geometries.values()].find(g=>g.supersedesGeometryId&&g.acceptedStatus==='ACCEPTED');t.beginPlayback(g.id);t.step(1);t.step(1);const intact=objects.every(({o,matrix,instances})=>JSON.stringify(o.matrix.toArray())===JSON.stringify(matrix)&&(!instances||JSON.stringify(Array.from(o.instanceMatrix.array))===JSON.stringify(instances)));return {checked:objects.length,intact};});assert(independence.checked>0);assert(independence.intact);
await page.locator('#historyMenu summary').click();await page.locator('#temporalReturn').click();assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState().mode),'current');assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.temporal.getState().visibleRecords.length),0);assert.equal(await page.evaluate(()=>window.PRAMAN_MAP.groups.parcels.visible),true);assert.deepEqual(errors,[]);
const report={baseline,playback:playback.map(p=>({type:p.type,eventId:p.eventId,phaseCounts:p.phases.map(s=>s.visibleRecords.length)})),correction,proposals:proposals.map(s=>s.visibleRecords),rollback,reconstruction:reconstruction.snapshot,independence,errors};fs.writeFileSync(path.resolve(__dirname,'../docs/temporal-runtime-validation.json'),JSON.stringify(report,null,2));console.log('PASS: temporal modes, historical search, split/merge/cross-cell playback, boundary changes, proposed/rejected separation, rollback, time reconstruction, history navigation and independent buildings.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
