import path from 'node:path';
import assert from 'node:assert/strict';
import { loadEvidenceGraphDataLayerFromDirectory } from './tests/nodeLoader.mjs';
import { buildIndividualParcelModeModel, buildAuthoritativeCanonicalStateModel, buildDistortionAwareMatchingModel, buildSourceArrivalModels, buildParcelHistoryLineageModel, ADAPTER_DEFINITIONS } from './src/evidence-graph/replay/index.mjs';
const root=process.cwd();
const layer=await loadEvidenceGraphDataLayerFromDirectory(path.join(root,'public','PRAMAN_DATA'));
const reps={clean_match:'IN-DL-110054-1-1',multiple_source_match:'IN-DL-110054-1-4',conflicted_parcel:'IN-DL-110054-1-10',human_reviewed_parcel:'IN-DL-110054-1-18',unresolved_parcel:'IN-DL-110054-1-18',split_parcel:'IN-DL-110054-1-101',merged_parcel:'IN-DL-110054-1-102',resurveyed_parcel:'IN-DL-110054-1-23',historical_parcel:'IN-DL-110054-1-101',rollback_or_rejected_transaction:'IN-DL-110054-1-20'};
const expected={sourceDatasetCount:7,sourceObservationCount:4366,activeCanonical:1000,historical:60,candidateAssociations:4583,accepted:753,ambiguous:281,rejected:26,unmatched:0,conflicts:715,reconciliationRows:1060,reconciledStatus:56,unresolved:286,humanReview:264};
const sourceModels=buildSourceArrivalModels(layer), matching=buildDistortionAwareMatchingModel(layer), finalModel=buildAuthoritativeCanonicalStateModel(layer);
assert.equal(sourceModels.length,expected.sourceDatasetCount); assert.equal(layer.tables.sourceObservations.length,expected.sourceObservationCount); assert.equal(layer.tables.canonicalParcels.length,expected.activeCanonical); assert.equal(layer.tables.historicalParcels.length,expected.historical); assert.equal(matching.candidateAssociations.length,expected.candidateAssociations); assert.equal(matching.outcomeGroups.ACCEPTED.count,expected.accepted); assert.equal(matching.outcomeGroups.AMBIGUOUS.count,expected.ambiguous); assert.equal(matching.outcomeGroups.REJECTED.count,expected.rejected); assert.equal(matching.unmatchedObservationIds.length,expected.unmatched); assert.equal(finalModel.summary.conflicts,expected.conflicts); assert.equal(layer.tables.reconciledParcels.length,expected.reconciliationRows); assert.equal(finalModel.summary.reconciledCases,expected.reconciledStatus); assert.equal(finalModel.summary.unresolvedCases,expected.unresolved); assert.equal(finalModel.summary.humanReviewCases,expected.humanReview);
function existsInTable(type,id){const T=layer.tables;const L={SourceDataset:[T.sourceMetadata,'source_id'],SourceObservation:[T.sourceObservations,'observation_id'],NormalizedObservation:[T.matchingInput,'observation_id'],Conflict:[T.conflicts,'conflict_id'],ReviewEvent:[T.geogitEvents,'event_id'],ReviewDecision:[T.geogitEvents,'event_id'],CanonicalParcel:[T.canonicalParcels,'canonical_parcel_id'],HistoricalParcel:[T.historicalParcels,'canonical_parcel_id'],GeometryVersion:[T.geometryVersions,'geometry_id'],GeoGitEvent:[T.geogitEvents,'event_id']};if(!L[type]) return null;const [rows,key]=L[type];return rows.some(r=>String(r[key])===String(id));}
const deterministic=new Set(['AdapterConcept','MatchCandidate','MatchDecision','ReconciliationProposal','AuthoritativeState','LineageTransaction','ConflictCheckpoint']);
const results=[];
for(const [kind,parcelId] of Object.entries(reps)){
 const model=buildIndividualParcelModeModel(layer,parcelId); assert.equal(model.found,true,`${kind}: model not found`);
 const recon=layer.tables.reconciledParcels.find(r=>r.canonical_parcel_id===parcelId)||null; const expectedObs=new Set(recon?.matchedSourceIds??[]);
 assert.deepEqual(new Set(model.nodes.filter(n=>n.type==='SourceObservation').map(n=>n.datasetRecordId)),expectedObs,`${kind}: source observation mismatch`);
 assert.deepEqual(new Set(model.nodes.filter(n=>n.type==='NormalizedObservation').map(n=>n.datasetRecordId)),expectedObs,`${kind}: normalized mismatch`);
 const sourceTypes=new Set([...expectedObs].map(id=>layer.tables.sourceObservations.find(o=>o.observation_id===id)?.source_type).filter(Boolean));
 const expectedAdapters=ADAPTER_DEFINITIONS.filter(a=>a.sourceTypes.some(t=>sourceTypes.has(t))).map(a=>a.id).sort(); assert.deepEqual(model.nodes.filter(n=>n.type==='AdapterConcept').map(n=>n.datasetRecordId).sort(),expectedAdapters,`${kind}: adapters mismatch`);
 let expectedCandidates=0; for(const id of expectedObs){const o=layer.tables.sourceObservations.find(x=>x.observation_id===id); expectedCandidates+=(o?.candidate_canonical_parcel_id?1:0)+(o?.alternateCandidateParcelIds?.length??0);} assert.equal(model.nodes.filter(n=>n.type==='MatchCandidate').length,expectedCandidates,`${kind}: candidates mismatch`);
 assert.equal(model.nodes.filter(n=>n.type==='MatchDecision').length,recon?1:0,`${kind}: decision mismatch`);
 const expectedConflicts=layer.tables.conflicts.filter(c=>c.canonical_parcel_id===parcelId); assert.equal(model.nodes.filter(n=>n.type==='Conflict').length,expectedConflicts.length,`${kind}: conflicts mismatch`); assert.equal(model.story.humanReview.required,Boolean(recon?.requiresHumanReview),`${kind}: review mismatch`);
 if(recon?.proposedState) assert.ok(model.nodes.some(n=>n.type==='ReconciliationProposal'),`${kind}: missing proposal`); if(recon?.authoritativeState) assert.ok(model.nodes.some(n=>n.type==='AuthoritativeState'),`${kind}: missing authority state`);
 const hist=buildParcelHistoryLineageModel(layer,parcelId); if(hist.found){assert.equal(model.nodes.filter(n=>n.type==='LineageTransaction').length,hist.transactions.length,`${kind}: lineage mismatch`);assert.equal(model.nodes.filter(n=>n.type==='GeometryVersion').length,hist.geometryVersions.length,`${kind}: geometry history mismatch`);}
 for(const node of model.nodes){const direct=existsInTable(node.type,node.datasetRecordId); if(direct===false) throw new Error(`${kind}: ${node.type} points to missing ${node.datasetRecordId}`); if(direct===null&&!deterministic.has(node.type)&&!['SourceDataset','SourceObservation','NormalizedObservation','Conflict','ReviewEvent','ReviewDecision','CanonicalParcel','HistoricalParcel','GeometryVersion','GeoGitEvent'].includes(node.type)) throw new Error(`${kind}: unsupported provenance type ${node.type}`); if(node.type==='LineageTransaction') assert.ok((node.memberRecordIds??[]).every(id=>layer.tables.parcelLineage.some(r=>r.lineage_event_id===id)),`${kind}: fake lineage member`);}
 results.push({kind,parcelId,nodes:model.nodes.length,edges:model.edges.length,sourceObservations:expectedObs.size,adapters:expectedAdapters.length,candidates:expectedCandidates,conflicts:expectedConflicts.length,reviewRequired:Boolean(recon?.requiresHumanReview),lineageTransactions:hist.found?hist.transactions.length:0,geometryVersions:hist.found?hist.geometryVersions.length:0,geogitEvents:hist.found?hist.geogitEvents.length:0,matchStatus:recon?.match_status??null,recordStatus:recon?.record_status??null});
}
console.log(JSON.stringify({diagnosticErrors:layer.getDiagnostics().filter(d=>d.severity==='ERROR').length,global:{sourceModels:sourceModels.length,candidateAssociations:matching.candidateAssociations.length,finalSummary:finalModel.summary,reconciliationRows:layer.tables.reconciledParcels.length},representatives:results},null,2));
